### ISSUE TITLE
container 'std.atomic' has no member called 'Int'

### ISSUE THREAD

**Issue by mountain** [frmdstryr/zhp#16]
Hello, @frmdstryr 

I am trying to setup the demo project under Zig 0.8.0, but meet compilation error as below:

```bash
./main.zig:107:29: error: container 'std.atomic' has no member called 'Int'
    var counter = std.atomic.Int(usize).init(0);
```

We met same error,  both on Mac or Ubuntu. It is zig 0.8.0_1 on Mac, and zig 0.8.0 on Ubuntu.

The codebase I am testing is zhp tag 0.8.0. 

In my understanding, zhp 0.8.0 targets zig 0.8.0? Is it correct?

**Comment by frmdstryr** [comment]
The demo repo needs updated.

The example folder within this repo is almost the same but is kept up to date.

**Comment by mountain** [comment]
Thanks, I will try another example.
