### ISSUE TITLE
Example in README.md causes a compilation error

### ISSUE THREAD

**Issue by MarcusWagberg** [frmdstryr/zhp#24]
line 20 in the example (line 63 in the README.md) currently reads: 
`web.Middleware.create(web.middleware.LoggingMiddleware);`

But this causes a compilation error:
`example.zig:20:60: error: expected ',', found ';'`

To fix this compilation error  line 20 in the example should be changed to:
`web.Middleware.create(web.middleware.LoggingMiddleware),`

**Comment by frmdstryr** [comment]
Thanks for pointing it out. Can you do a pull request?
